blueprint:
  name: Notification Script Blueprint
  author: tobiasabarbanell
  description: > 
    A script that does a notification on one or more mobile phones
  source_url: https://raw.githubusercontent.com/abarbanell/ha-blueprints/refs/heads/main/script/notification.yaml
  domain: script
  homeassistant:
    min_version: 2024.11.0
  input:
    notify_device:
      name: Devices
      default: ""
      selector:
        device:
          integration: mobile_app
          multiple: false
sequence:
  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: "{{ title }}"
    message: "{{ message }}"

fields:
  title:
    selector:
      text:
        multiline: false
        type: text
    name: title
    description: Enter a title for your notification
    required: true
  message:
    selector:
      text:
        multiline: false
        type: text
    name: message
    description: Enter message for your notification
    required: true