blueprint:
  name: Notification Script Blueprint
  author: tobiasabarbanell
  description: > 
    A script that sends a notification to one or more mobile phones
  source_url: https://raw.githubusercontent.com/abarbanell/ha-blueprints/refs/heads/main/script/notification.yaml
  domain: script
  homeassistant:
    min_version: 2024.11.0
  input:
    notify_devices:
      name: Mobile devices
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true
    tag:
      name: Tag for messages
      default: "no-tag"
sequence:
  - alias: "Send mobile notification"
    repeat:
      for_each: !input notify_devices
      sequence:
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: >
              {% if tag %}
                {{ tag }} - {{ title }}
              {% else %} 
                {{ title }}
              {% endif %}
            message: "{{ message }}"

variables:
  tag: !input tag
    # name: tag
    # description: tag for each message
    # required: false
    # selector:
    #   text:
    #     multiline: false
    #     type: text

fields:
  title:
    selector:
      text:
        multiline: false
        type: text
    name: title
    description: Enter a title for your notification
    required: true
  message:
    selector:
      text:
        multiline: true
        type: text
    name: message
    description: Enter message for your notification
    required: true